name = "FrostSMP"
author = "frost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f344961fc9663e4807936cf28980ad332cdb14ad821cae11c1052db10983dbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
