name = "FrostSMP"
author = "Frost SMP Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3391c30d333740c54d61e3ad8470c9ae863e7d7ddee0ad49a6de8e103644b94e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"

[options]
acceptable-game-versions = ["1.21.1"]
